### PR TITLE
Set up repository for Continuous Integration

### PR DESCRIPTION
**Pull request by robertodr**
Sorry for sending the PR from `master`...

- Each recipe is in its own folder `recipe-XYZU`. Each folder has a README.md that explains a bit what's going on.
- Integrate with Travis CI for Linux and Mac OS X.
  These builds use both Unix Makefiles and Ninja as generators.
- Integrate with AppVeyor CI for Windows. The build matrix exercises both Visual Studio and MinGW as compilers. For MinGW, Unix Makefiles and Ninja are used as generators. There is also a build with Visual Studio and Ninja, that shows how CMake is smart enough to automatically pick up a compiler that works with the chosen generator.
- On Linux, Mac OS X and Windows, reasonably recent versions of the toolstack are installed. In particular, the Ninja version maintained by Kitware is installed, since that's the one that works also with Fortran projects.
- I have added badges to the main README.md.
- The CI jobs are wrapped into a Python script that configures, builds and tests (if needed/makes sense). The Python script loops over recipes, `cd`-s, runs CMake to configure, runs CMake to build and CTest to test.

@bast you will have to:
- Change the links in the badges.
- Activate both Travis and AppVeyor.
- For Travis, you will have to export a token for Homebrew to work without bogging down (or even timing out) the build.

### CODE REVIEW

**Comment by bast** [comment]
Thanks Roberto! I will catch up with this today.

**Comment by robertodr** [comment]
I'll squash for a meaningful history.

**Comment by bast** [comment]
I think the history is fine. OK for me to merge? Travis and Appveyor are active. Badge rename later is roger. Only not clear to me how to the Homebrew part.

**Comment by robertodr** [comment]
Have a look here: https://github.com/Homebrew/homebrew-php/issues/2786
Or you can give me access to the repo settings and I can do it.

**Comment by bast** [comment]
HOMEBREW_GITHUB_API_TOKEN added.

**Pull request merged**
