### PR TITLE
Add final recipe in Chapter 6

### PR DESCRIPTION
**Pull request by robertodr**
This recipe shows how to use Python to generate code. With this example I want to show how one can have an intermediate code generation layer that can be shared among different build systems for the same code.

### CODE REVIEW

**Comment by bast** [comment]
I like the example. Only unsure about the coloring commit. Is it intentionally part of the PR?

**Comment by robertodr** [comment]
That commit is intentional, yes. Colors are not output on Travis though. I think it's still convenient to have them when testing locally.

**Comment by bast** [comment]
Strange thing is that colors do show up when I look at the test result in this PR. Mac seems broken but probably not thanks to this PR. Merging in a moment.

**Comment by robertodr** [comment]
They do. Weirdly weird. Maybe they are only rendered when the CI job is done and not when following the output stream, as I was doing? Mac OS X was broken by the caching PR.

**Pull request merged**
