### PR TITLE
Use dollar origin for rpath

### PR DESCRIPTION
**Pull request by TheErk**
It may be a be better example to use $ORIGIN mechanism when setting up RPATH than using
absolute install path computed from prefix that could be changed at install time.
 
$ORIGIN is more robust because it should tolerate relocation of the prefix
http://longwei.github.io/rpath_origin/

CMake should handle $ORIGIN as part or RPATH value since a long time ago:
https://cmake.org/pipermail/cmake/2008-January/019290.html
https://public.kitware.com/pipermail/cmake/2008-August/023259.html

### CODE REVIEW

**Comment by bast** [comment]
Thanks Eric!

**Comment by robertodr** [comment]
Thanks! Can you squash the merge commits?

**Comment by TheErk** [comment]
I did forced-push a cleaner  branch and it looks like this triggers the merge. Is it right? Is it Ok on your side?

**Comment by TheErk** [comment]
I made a mistake...
I forced-pushed without commiting locally. Silly me.
Re-opening it.

**Comment by TheErk** [comment]
Sorry about that.

**Comment by bast** [comment]
Thanks Eric - looks good, sorry for extra work! There was also the other commit to fix imports, would you like to submit it as separate PR?

**Comment by TheErk** [comment]
I think imported target issue was already merged through this PR https://github.com/bast/cmake-recipes/pull/224.

Or are you speaking of something else I don't remember?

**Comment by robertodr** [comment]
That was indeed already merged in.

**Comment by bast** [comment]
Ah yes OK - I thought I had a deja vu on that change :-) I will wait for the CI and then merge - thank you again!

**Pull request merged**
