### PR TITLE
Cache anaconda on Travis

### PR DESCRIPTION
**Pull request by robertodr**
As per #261

### CODE REVIEW

**Comment by robertodr** [comment]
Waiting on Mac OS X, which refuses to boot :( To check that the caching actually works, restart the build when it's done and observe the output from the `install_dependencies.sh` script.

**Comment by robertodr** [comment]
Restarting the builds showed that caching didn't work. I am troubleshooting. I'll ping you when this is ready to go again.

**Comment by robertodr** [comment]
@bast this is OK to squash-merge now. In case caching still doesn't I'll take another look.

**Comment by bast** [comment]
I will rebase the 3.5/3.10 on top of this.

**Pull request merged**
