### PR TITLE
Chapter 9: recipes 1 and 2

### PR DESCRIPTION
**Pull request by robertodr**
As promised, these are the first two recipes for chapter 9, plus scaffolding for the rest. Main point of these two recipes is to show what to do when there is no direct access to the C or Fortran code we want to interoperate with:
 - [x] The first recipe is not specifically about CMake usage, but I thought "what the heck, this is valuable learning". The source code shows how to wrap system libraries for UUID and backtraces (written in C) using `iso_c_binding`. The CMake code shows how to structure the `CMakeLists.txt` for maximum locality of variables and maximum enjoyment. This is stuff we already see in chapter 8, but I think it's nice to drive the point home as thoroughly as possible.
 - [x] The second recipe shows the other side of the coin. That is system libraries in Fortran (BLAS/LAPACK) to be used in C++. This recipe is basically the same as one in Chapter 3. So I'll probably just move that one here 😸 @bast what do you say?
 - [x] I've moved recipe 4 from chapter 3 here and reorganized the sources a bit. I reworked recipe 4 in chapter 3 to show the nitty-gritty use of BLAS/LAPACK doing symbol mangling by hand. This will give a better incentive to read on until recipe 2 in chapter 9. I have to modify text on TC

### CODE REVIEW

**Comment by bast** [comment]
Good idea. I agree with both points :-)

**Comment by robertodr** [comment]
OK cool! I'll move one recipe from chapter 3 here. For the other planned recipes in this chapter, do you want to use the bank example in [bast/context-api-example](https://github.com/bast/context-api-example)? I can put some scaffolding (basically copy-pasting the code) into this PR.

**Comment by bast** [comment]
I am thinking about a good example and the bank example might be actually OK. I really like the context part of it and this would be also a good excuse to brush it up to more modern CMake. I would like to use objects here. Typically animals are good for objects (walk, eat, bark) but then one often has to mess with strings and I want to keep this example with floats and integers so the banking one might be good. But other suggestions welcome.

**Comment by robertodr** [comment]
I'll think about it a little more then 👍

**Comment by bast** [comment]
Looks good so far! The linear algebra example will be very useful.

**Comment by bast** [comment]
Is it OK if I merge this and we do the rest in a separate PR(s)? This is because I need to base my work on the scaffold that is part of this change.

**Comment by bast** [comment]
And I thought about and will probably go for the bank example because it is easy to understand and explain without going into too many sidetracks and I can do all 3 techs with one use case.

**Comment by robertodr** [comment]
Yes, ready to be merged! Should have updated the comment 😄

**Pull request merged**
