### PR TITLE
Make use of caching on Travis

### PR DESCRIPTION
**Pull request by robertodr**
This speeds up builds significantly, since we won't have to download/build the dependencies all the time. It doesn't work on Mac OS X currently, so probably hold off merging until I have the patience to troubleshoot it. I have also reworked the way the script handles arguments and now we can ask for verbose builds. You might want to cherry-pick that commit before this one gets merged.

### CODE REVIEW

**Comment by bast** [comment]
Fantastic! How about I merge and we troubleshoot the OS X later? My understanding is that only the caching does not work on OS X which would mean that globally the situation is better than before.

**Comment by robertodr** [comment]
Sounds good. OS X is a lot of work to maintain, sadly.

**Comment by bast** [comment]
The test now fails on OS X - is this expected and is it OK if we merge? Or should I rather wait and we try to fix this to not get the red color back?

**Comment by robertodr** [comment]
Let's merge it. I'd rather not have red. But this is necessary evil towards
greater greenery.

**Pull request merged**
