### PR TITLE
limit testing to chapter 1 to rebuild dependency cache

### PR DESCRIPTION
**Pull request by bast**
once the cache is rebuilt, we reactivate all chapters again

### CODE REVIEW

**Comment by bast** [comment]
Let's first see whether we get an all-green Travis. If yes, we can try to merge this to convince Travis to cache dependencies on master.

**Comment by bast** [comment]
This now finally passes Travis (only chapter 1 tested). Should we merge this and see whether it creates a cache for us?

**Comment by bast** [comment]
In case #283 finishes green there might be no need for this one. Let's see.

**Comment by bast** [comment]
Nope, we are timing out on master currently. Can we try this trick to get the precious cache?

**Comment by robertodr** [comment]
Sure. Should I merge this one?

**Comment by bast** [comment]
Yes please.

**Pull request merged**
