### PR TITLE
 on Travis Linux test on CMake 3.5 and 3.10

### PR DESCRIPTION
**Pull request by bast**
On 3.5 a number of recipes fail. Not sure whether we want to clean them up as part of this PR?

### CODE REVIEW

**Comment by bast** [comment]
At least for one recipe we will need to implement an expected failure on CMake 3.5 (chapter 2, recipe 5).

**Comment by robertodr** [comment]
I'd prefer this to be green on Travis, but I understand if you don't want to devote more effort on CI in this round.

**Comment by bast** [comment]
OK let's fix the 3.5 in this PR.

**Comment by bast** [comment]
I am working on the fixes. I do that on a side-branch where I can do some ugly temporary commits to speed up testing.

**Comment by bast** [comment]
There is still work left:
- [ ] 3/6
- [ ] 3/7
- [ ] 3/9
- [ ] 3/10
- [ ] 5/6
- [ ] 5/8
- [ ] 7/3
- [ ] 9/1
- [ ] 10/4
- [ ] 10/5
- [ ] 11/1
- [ ] 11/2
- [ ] 11/3
- [ ] 11/4
- [ ] 11/5

**Comment by bast** [comment]
Note to myself to extract minimum version from `CMakeLists.txt` directly, then we don't have to track it in two places.

**Comment by bast** [comment]
I think 11/1-5 should be merged before they are adapted.

**Comment by bast** [comment]
And I don't understand how 10/5 works so I leave that for the moment.

**Comment by bast** [comment]
I got a bit exhausted with this and think that the rest should be done after the merge. I think this will not hurt us too much since for every other PR it's easy to find out if it works on 3.10 and on OS X (3.9).

**Pull request merged**
