### PR TITLE
Finalizing recipes for Chapter 3

### PR DESCRIPTION
**Pull request by robertodr**
@bast Review when I'm done with last recipe :wink:

### CODE REVIEW

**Comment by bast** [comment]
OK - so I understand I should wait with review?

**Comment by bast** [comment]
To make that more clear in future I recommend to mark WIP pull requests with [WIP].

**Comment by robertodr** [comment]
Yes, I should have marked it [WIP] in the title. Sorry for that.

**Comment by robertodr** [comment]
CI keeps failing, sadly. I can't seem to fix the dependencies even on Linux!

**Comment by bast** [comment]
I recommend to un-WIP and merge and later we clean things up. This is something for late night when I don't need much thinking power.

**Comment by bast** [comment]
I am worried that the explicit `gfortran-5` etc. will completely break stuff on my laptop/desktop where these do not exist.

**Comment by robertodr** [comment]
Ah, that's true... I had not thought about this problem... I have no clever solution at the moment. I was trying to get the CI working. It seems that to get MPI to work on Travis you need to unset the CC, FC and CXX environment variables: https://docs.travis-ci.com/user/languages/c/#MPI-projects

**Comment by bast** [comment]
Interesting and another support against these env vars. How about using the version unspecific gcc, gfortran, g++ and making sure they are the right version by the powers of Travis/Appveyor?

**Comment by robertodr** [comment]
That's fine by me. Just don't use `<regex>` in C++ examples :smile_cat: By the way the Travis error at the installation step baffles me:
```
The Open MPI wrapper compiler was unable to find the specified compiler
gfortran in your PATH.
Note that this compiler was either specified at configure time or in
one of several possible environment variables.
```

**Comment by robertodr** [comment]
Works for Linux with Unix Makefiles. Ninja can no longer get a handle on gfortran and crashes. Can IMO be merged as-is.

**Comment by bast** [comment]
Awesome!

**Pull request merged**
