### PR TITLE
Last recipes in Chapter 5

### PR DESCRIPTION
**Pull request by robertodr**
I need to write them up on TypeCloud, so hold off merging this one (I might have to fix the recipes on the way)
Recipe 9 can be a starting point for writing a function (or functions) to set compiler flags according to availability and compiler vendor. This is my current thinking on the matter:
1. Compiler flags have to be set using `target_compile_options`, so that dependents can pick them up automatically based on the visibility, _i.e._ `PUBLIC`, `INTERFACE, `PRIVATE`
2. For absolutely no reason in the world `CMAKE_<LANG>_FLAGS_<CONFIG>` should be touched _inside_ any of the `CMakeLists.txt`
3. Compiler flags should be checked for availability with respect to compiler vendor and version. A corner case might be user-specified `CMAKE_<LANG>_FLAGS` from command line (have to think a bit more about this)
4. Within the project flags should be set in variables like `<PROJECT>_<LANG>_FLAGS_<CONFIG>`, but only after the availability checks have been run.
5. Targets get their variables set with generator expressions:
```
target_compile_options(foo
  PRIVATE
      $<$<CONFIG:DEBUG>:${${PROJECT_NAME}_<LANG>_FLAGS_DEBUG}>
      $<$<CONFIG:RELEASE>:${${PROJECT_NAME}_<LANG>_FLAGS_RELEASE}>
 )
```

### CODE REVIEW

**Comment by bast** [comment]
Great work and great learning for me!

**Comment by bast** [comment]
So the keywords is "scope" right? We want to avoid the "traditional" variable way to avoid flooding the global scope with flags and definitions, correct?

**Comment by robertodr** [comment]
You would still have variables, but you would use them directly _if and only if_ they have very restricted scope, _i.e._ they are in a leaf `CMakeLists.txt`. And by leaf I mean at the end of the directory hierarchy. Global variables can still be used, but they _must not_ touch stuff that CMake defines on its own, unless that's the way they are supposed to work, _e.g._ `CMAKE_CXX_STANDARD_REQUIRED` (though that's still questionable)

Here's how the keywords work for `target_<command>(<target-name> ...)`, it's explained on the CMake docs too:
 - `PRIVATE` stuff only applies to `<target-name>` and none of its dependents.
 - `INTERFACE` stuff only applies to **dependents** of `<target-name>`.
 - `PUBLIC` stuff applies to `<target-name>` **and** dependents.

You can see how this makes easy propagating link libraries, compiler flags, include directories and compiler definitions to targets across the project. No need to have a bunch of global variables defined at the very beginning and then jumping through hoops to modify them downstream and keep everything up to date (oh! The pain of doing `include_directories` from a leaf `CMakeLists.txt`!!!)
Moreover, these build requirements can become _usage_ requirements for projects using your project. Meaning that at build system generation you have the whole recipe to build **and** use your library/program afterwards.

**Comment by bast** [comment]
Thanks for explanation. I fully agree. Once we are done with this I need to revisit all the codes where I left a lot of ugliness.

**Comment by bast** [comment]
Some test(s) is/are failing (on Travis). I can probably fix it but want to fix first before merging. Unless the failing test is what you mean by "weirdness"?

**Comment by robertodr** [comment]
Hopefully this fixes it. I suspect Drone is using an old image

**Comment by bast** [comment]
What we can also do is that I merge and then I can try to debug that stuff with a new PR?

**Comment by robertodr** [comment]
Fine by me!

**Pull request merged**
