### PR TITLE
bump cmake to 3.11.1; fixes #337

### LINKED ISSUE #337: Bump Travis to 3.11.1
This is not urgent and I will do it later, just that I don't forget.

### PR DESCRIPTION
**Pull request by bast**
Hopefully a trivial change without any breakage.

### CODE REVIEW

**Comment by robertodr** [comment]
The infamous Anaconda recipe times out and the update was not picked up.

**Comment by bast** [comment]
But don't we inherit the version already? Should I split off the Anaconda into an own Travis matrix element so that we get less of these false negatives?

**Comment by robertodr** [comment]
Yes, we do, sorry about the false alarm. I guess we need to purge the cache? When you check the output from Travis it says that CMake was found in cache, even though that path shouldn't be there...
If you can split off Anaconda, it would be a boon. Without HDF5 builds are much faster, but these random failure make it a tiny bit more annoying to review things...

**Comment by bast** [comment]
OK I will refactor a bit the Travis testing. We can keep this one open until then.

**Comment by robertodr** [comment]
FYI, 3.11.2 is out :smile_cat:

**Comment by bast** [comment]
Self-assigning ...

**Pull request closed without merging**
