### PR TITLE
Fix Eigen example

### PR DESCRIPTION
**Pull request by robertodr**
Let's get Travis and Drone green!

### CODE REVIEW

**Comment by robertodr** [comment]
I see some greenery on Travis for Linux. Working on Mac OS X while the Docker image for Drone gets rebuilt :smile_cat:

**Comment by robertodr** [comment]
The Eigen recipe will need to be updated on TypeCloud.

**Comment by bast** [comment]
Eigen issue is followed-up in #156.

**Comment by bast** [comment]
Issue with libuuid recipe on Travis OS X is followed-up in #157.

**Comment by bast** [comment]
Thanks! Great work! Merging.

**Pull request merged**
